version: '3.9'
services:
    java-maven-app:
      image: otobongedoho18361/demo-app:${IMAGE_NAME}
      ports:
        - 8080:8080
    postgres:
      image: postgres:17
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=changethis123
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
